### ISSUE TITLE
Додайте цих постачальників

### ISSUE THREAD

**Issue by ghost** [CakesTwix/cloudstream-extensions-uk#10]
Я знайшов пару сайтів, якщо маєте час можете додати:
- https://filmoteka.cc/
- https://ua-cinema.com/
- https://kino4ua.com/

**Comment by CakesTwix** [comment]
Дякую, але ці сайти не дуже подобаються
Реклама порн-ігор, казино. Це одна з причин, чому ненавиджу піратські сайти.
На даний момент є два сайти, яких у планах. Так само потрібно почистити гівнокод свій, а то соромно
А також там є російська озвучка, тому ще сильніше не хочу

**Comment by NoName3045** [comment]
В мене стоїть блокувальник реклами тому я не знав що вони казино рекламують😅

**Comment by MrIkso** [comment]
Непогано би додати https://simpsonsua.tv/
Хоча всі ці сайти це лише каталоги,  балансери то одні і теж (tortuga.wtf і ashdi.vip)

**Comment by CakesTwix** [comment]
Добре, мб почну сьогодні

**Comment by CakesTwix** [comment]
> Непогано би додати https://simpsonsua.tv/ Хоча всі ці сайти це лише каталоги, балансери то одні і теж (tortuga.wtf і ashdi.vip)

Вирішив вивчити сайт, чомусь був увімкнений адблок, вимкнув і... реклама казино. Ненавиджу.
А ще коментарі в коді сторінки російською мовою.

**Comment by l3x71** [comment]
https://uaspeedfilms.club/ ?

**Comment by LikenPlay** [comment]
Новий сайт для перегляду аніме — animeua.club

**Comment by Fqwe1** [comment]
https://ekino.pro/

**Comment by CakesTwix** [comment]
https://hentaiukr.com/ :))))))))))))))))))))))))))

**Comment by CakesTwix** [comment]
> https://ekino.pro/

Після хентая

**Comment by Fqwe1** [comment]
А чи вийде додати https://1plus1.video/ (безкоштовний контент)?

**Comment by CakesTwix** [comment]
> А чи вийде додати https://1plus1.video/ (безкоштовний контент)?

Там контент зашифрований. На самому початку теж хотів, але на жаль

**Comment by Fqwe1** [comment]
https://ua-warez.com/

**Comment by Fqwe1** [comment]
https://vodnerilo.com/

**Comment by CakesTwix** [comment]
> https://vodnerilo.com/

https://github.com/CakesTwix/cloudstream-extensions-uk/commit/d07a0c89f1832c3ea39e7dbd53530bcd2dd76ed0

**Comment by Fqwe1** [comment]
https://teleportal.ua/
https://multok.com/

**Comment by LikenPlay** [comment]
https://www.unimay.media/

**Comment by CakesTwix** [comment]
> https://www.unimay.media/

Звучить дуже смачно, бачив їх на приватному торрент треккері
А ще помітив, що є API, спробую зробити

**Comment by CakesTwix** [comment]
Цей Issue більше не актуальний. Для запиту на додавання сайту слід використовувати [Issue Template](https://github.com/CakesTwix/cloudstream-extensions-uk/issues/new?assignees=&labels=new-source&projects=&template=new_source.yml)
