### ISSUE TITLE
[Uakino] аніме Наруто відображається як фільм

### ISSUE THREAD

**Issue by l3x71** [CakesTwix/cloudstream-extensions-uk#16]
Відкривається перша серія а інші серії всунуті в джерела без нумерації
![скрін 1](https://user-images.githubusercontent.com/78854695/232889596-3b3a968a-91c8-4f17-8070-fa8cb88c7e01.jpg)
![скрін 2](https://user-images.githubusercontent.com/78854695/232889614-0a9f6846-967e-49e6-beb0-c0d94522c6f2.jpg)

**Comment by CakesTwix** [comment]
Про проблему давно відомо, ніяк не доходять руки. Зараз спробую виправити

**Comment by CakesTwix** [comment]
https://github.com/CakesTwix/cloudstream-extensions-uk/commit/64c8bca5b34148f96d447cf5d52035de0ee6f8ed

Конкретно Наруто виправив, але міг поламати щось інше.
