### ISSUE TITLE
Додайте новий сайт

### ISSUE THREAD

**Issue by Fqwe1** [CakesTwix/cloudstream-extensions-uk#18]
Добрий день, будь ласка, додайте сайт https://uatyan.com/ для перегляду аніме. Дякую

**Comment by CakesTwix** [comment]
@Fqwe1, добре, додам, коли буде час.

**Comment by Zeddy-Coder** [comment]
> @Fqwe1, добре, додам, коли буде час.

Прошу якщо вже і додавати його, то якось окремо, бо це сайт від даберки що досі співпрацює з російською командою озвучки
