### ISSUE TITLE
Bug anitube.in.ua

### ISSUE THREAD

**Issue by Fqwe1** [CakesTwix/cloudstream-extensions-uk#19]
![screenshot](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/139431054/c9fa44b3-2021-4feb-af98-c6a71715f4c1)
Багато 0-их серій, які рахуються як справжні

**Comment by Fqwe1** [comment]
![Screenshot](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/139431054/de44365d-1715-47e7-9f9f-aac73d718ae0)
Зайвий символ в назві

**Comment by CakesTwix** [comment]
Як же набрид цей анитубе, немає бажання його фіксувати. Використовуйте інші джерела.
