### ISSUE TITLE
Поліпшення UaSerial

### ISSUE THREAD

**Issue by Fqwe1** [CakesTwix/cloudstream-extensions-uk#20]
Якщо можливо додайте список акторів та підтримку другого плеєру, дякую
![Screenshot](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/139431054/f2a9e4fe-35ed-44b2-bb6c-caf8cd82fe6d)

**Comment by CakesTwix** [comment]
Добре, зроблю

**Comment by CakesTwix** [comment]
https://github.com/CakesTwix/cloudstream-extensions-uk/commit/9efaa4c301b0d6eb980cc0872535a1b947ff3768
Акторів додав, плеєр ні, чому? 
![image](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/57946485/96b90058-193b-4c8b-812d-0d376872f93c)
![image](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/57946485/9b061395-c327-45ef-ae44-3c9b1efe9964)
