### ISSUE TITLE
Aniage поліпшення

### ISSUE THREAD

**Issue by Fqwe1** [CakesTwix/cloudstream-extensions-uk#22]
Додайте трейлер

Приклад аніме з трейлером:
https://www.aniage.net/watch/5ef35778-fe65-4535-a6ff-a27749549af6

**Comment by CakesTwix** [comment]
https://github.com/CakesTwix/cloudstream-extensions-uk/commit/1b901dc389704ed826593192c743d2492271c0a0
Хотів як раз)
