### ISSUE TITLE
UFDub bug

### ISSUE THREAD

**Issue by Fqwe1** [CakesTwix/cloudstream-extensions-uk#23]
Фільм відображається, як аніме
![Screenshot](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/139431054/6362d473-0e58-4f36-adc8-5f88a4eea1b6)

**Comment by CakesTwix** [comment]
https://github.com/CakesTwix/cloudstream-extensions-uk/blob/master/UFDubProvider/src/main/kotlin/com/lagradost/UFDubProvider.kt#L90
Треба виправляти, дякую

**Comment by CakesTwix** [comment]
https://github.com/CakesTwix/cloudstream-extensions-uk/commit/4052315c08bb434b6845d8dc8dd18a91c7a73a5b
+ виправив рекомендації
