### ISSUE TITLE
Aniage bug

### ISSUE THREAD

**Issue by Fqwe1** [CakesTwix/cloudstream-extensions-uk#25]
**Назва розширення**
Aniage

**Опис помилки**
![Screenshot](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/139431054/783d1d6e-ffa0-4bc4-9dc5-0b920b4c352a)
(На сайті все працює)

**Як повторити помилку**
Просто відкрив аніме "Ван піс"

**Що очікували**
Очікував подивитись аніме :)

**Скріншоти**
(Прикріпив до опису)

**Додатковий контекст**
Немає

**Comment by CakesTwix** [comment]
![Screenshot_20230823-235210_CloudStream](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/57946485/21aea7f8-4113-4b24-97ca-51b54e457bba)

**Comment by CakesTwix** [comment]
Якщо у вас все одно ця помилка, то напишіть мені в ЛС телеграму. Скину дебаг-версію, щоб дізнатися що ви там не те отримуєте

**Comment by Fqwe1** [comment]
> Якщо у вас все одно ця помилка, то напишіть мені в ЛС телеграму. Скину дебаг-версію, щоб дізнатися що ви там не те отримуєте

Зараз не отримую цю помилку, може це баг з Cloudstream?

**Comment by CakesTwix** [comment]
Це не CS3, Aniage відправив шось не те
