### ISSUE TITLE
Uakino bug

### ISSUE THREAD

**Issue by Fqwe1** [CakesTwix/cloudstream-extensions-uk#26]
**Назва розширення**
Uakino

**Опис помилки**
При пошуку "барбі", видає [статтю](https://uakino.club/news/17849-barbi-matyme-versiiu-imax-iz-dodatkovymy-kadramy-pislia-tytriv.html), а не фільм

**Як повторити помилку**
Кроки для відтворення поведінки:
1. Ввести в пошук "барбі"
2. Натиснути на перший постер
![Screenshot](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/139431054/4f249a58-e7a7-4698-b7ea-81d39fcf952c)

**Що очікували**
Очікував подивитися фільм, а що ще очікувати?)

**Скріншоти**
![Screenshot](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/139431054/fa82db8a-ddca-4af1-aeed-967a2c7d2073)

**Додатковий контекст**
https://uakino.club/news/17849-barbi-matyme-versiiu-imax-iz-dodatkovymy-kadramy-pislia-tytriv.html

**Comment by CakesTwix** [comment]
Хм, потрібно буде перевіряти посилання на наявність потрібних нам рядків
https://uakino.club/**cartoon/features**/15313-barb-yak-rapuncel.html
https://uakino.club/**cartoon/cartoonseries**/14276-barbi-prygody-v-budynku-mrii-2-sezon.html

Не парсимо, пропускаємо
https://uakino.club/**news**/17849-barbi-matyme-versiiu-imax-iz-dodatkovymy-kadramy-pislia-tytriv.html
https://uakino.club/**franchise**/15333-barb.html

Завтра вже пофікшу

**Comment by CakesTwix** [comment]
@Fqwe1, проблему виправило?

**Comment by Fqwe1** [comment]
> @Fqwe1, проблему виправило?

Не виправило, досі їх бачу. Версія актуальна (5)

**Comment by CakesTwix** [comment]
Упс, у тому комміті полагодив не для пошуку. Цього разу вже точно має виправити

**Comment by Fqwe1** [comment]
> Упс, у тому комміті полагодив не для пошуку. Цього разу вже точно має виправити

Працює! Дякую за вашу працю!
