### ISSUE TITLE
UaSpeedFilms

### ISSUE THREAD

**Issue by Fqwe1** [CakesTwix/cloudstream-extensions-uk#27]
### Назва сайту

UaSpeedFilms

### Посилання на сайт

https://uaspeedfilms.club/

### Корисна інформація для парсингу

Плеєр ASHDI

### Який тип медія там є?

- [X] Фільми
- [X] Серіали
- [X] Мультфільми
- [X] Мультсеріали
- [X] Аніме
- [ ] Дорами
- [ ] 🍓 18+

**Comment by CakesTwix** [comment]
Швидко)
Дякую за тестування, спробую додати

**Comment by CakesTwix** [comment]
Хотів сьогодні написати, але з якоїсь причини сайт лежить

**Comment by CakesTwix** [comment]
Походу, сайт закрили
