### ISSUE TITLE
Teleportal

### ISSUE THREAD

**Issue by Fqwe1** [CakesTwix/cloudstream-extensions-uk#28]
### Назва сайту

Teleportal

### Посилання на сайт

https://teleportal.ua/

#### Пошук:
https://tp-back.starlight.digital/ua/live-search?q=<Запит>
Повертає JSON

### Інша інформація

Різні ТБ шоу, яких немає у інших постачальників

### Який тип медія там є?

- [X] Фільми
- [X] Серіали
- [ ] Мультфільми
- [ ] Мультсеріали
- [ ] Аніме
- [ ] Дорами
- [ ] 🍓 18+

**Comment by CakesTwix** [comment]
![Screenshot_20230919-131424_CloudStream](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/57946485/36738d06-05b9-404f-a2d5-0c213182a177)
Вирішив почати цей сайт парсити. Як виявляється, у них є якийсь додаток під пк, телефон, ТВ. Ну так гаразд

Картинки у них не дуже підходять під розмір звичайних зображень у піратів. Поки тільки це зробив

**Comment by CakesTwix** [comment]
![Screenshot_20230919-133226_CloudStream](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/57946485/c191d8dc-43ba-4d3b-80a1-b90805571032)
Зате тут оч добре)

**Comment by CakesTwix** [comment]
![image](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/57946485/6c5fb5fe-f573-44a8-ad69-768fa0766d24)
Нашвидкуруч зробив. Тепер залишається адаптувати під усі медіа, що там є

**Comment by CakesTwix** [comment]
https://github.com/CakesTwix/cloudstream-extensions-uk/commit/a709aa7c28f1ad149ade967fc58469bd8c2f25a6
