### ISSUE TITLE
[Error] Unimay

### ISSUE THREAD

**Issue by Fqwe1** [CakesTwix/cloudstream-extensions-uk#29]
**Назва розширення**
Unimay

**Опис помилки**
Не вдається загрузити контент - видає помилку

P.s. переходив за посиланням воно працює

**Як повторити помилку**
1. Вибрати Unimay
2. Клацнути на будь-яке аніме

**Що очікували**
Очікував звичайне відкриття аніме

**Скріншоти**
![Screenshot_Cloudstream](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/139431054/f243ada4-21ce-4523-b186-bdce30a0d79e)

**Додатковий контекст**
Немає

**Comment by CakesTwix** [comment]
https://github.com/CakesTwix/cloudstream-extensions-uk/commit/938534166acbd16832bf62ecf2d1a12257e274e3
