### ISSUE TITLE
Higotv

### ISSUE THREAD

**Issue by LikenPlay** [CakesTwix/cloudstream-extensions-uk#30]
### Назва сайту

HiGoTv

### Посилання на сайт

https://higotv.fun/

### Який тип медія там є?

- [ ] Фільми
- [ ] Серіали
- [ ] Мультфільми
- [ ] Мультсеріали
- [X] Аніме
- [ ] Дорами
- [ ] 🍓 18+

**Comment by CakesTwix** [comment]
Done.
https://github.com/CakesTwix/cloudstream-extensions-uk/commit/ee5799b734e1590019f73167529136b65df6c776
