### ISSUE TITLE
Moviestape

### ISSUE THREAD

**Issue by IZVERG011** [CakesTwix/cloudstream-extensions-uk#34]
### Назва сайту

Moviestape

### Посилання на сайт

http://moviestape.net/

### Який тип медія там є?

- [X] Фільми
- [X] Серіали
- [X] Мультфільми
- [X] Мультсеріали
- [ ] Аніме
- [ ] Дорами
- [ ] 🍓 18+

**Comment by CakesTwix** [comment]
Якийсь страшний та http-only сайт.
