### ISSUE TITLE
Серії нових тайтлів на anitube не відображаються 

### ISSUE THREAD

**Issue by Tisteos** [CakesTwix/cloudstream-extensions-uk#35]
**Назва розширення**
Anitube.in.ua

**Опис помилки**
При переході на нові тайтли, в яких вже є декілька серій, пише "скоро буде"

**Як повторити помилку**
Увімкнути розширення anitube та зайти на будь який новий тайтл 

**Скріншоти**
![Screenshot_2024-01-25-23-12-17-268_com lagradost cloudstream3-edit](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/111273978/a24daac8-7756-490b-91e7-103d7eb89768)

**Comment by CakesTwix** [comment]
Це тому що я не додав усіх плеєрів.
Додавати їх всі у мене немає бажання і деякі з них русяві. Не буду проти прийняти пул реквест, якщо він буде
Рекомендую дивитися з Watari, AnimeUA
