### ISSUE TITLE
[Bug] HigoTV

### ISSUE THREAD

**Issue by Fqwe1** [CakesTwix/cloudstream-extensions-uk#36]
**Назва розширення**
HigoTV

**Опис помилки**
Зайвий текст в назві тайтлів

**Скріншоти**
![Screenshot](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/139431054/ef9d06f6-25ec-408c-b8db-98f7df7c26c4)

**Додатковий контекст**
Баг зв'язаний з тим, що на сайті є три теги greed-item__title_p.
Перший - назва тайтлу
Другий - кількість серій
Третій - стан аніме

**Comment by CakesTwix** [comment]
Fixed, дякую
https://github.com/CakesTwix/cloudstream-extensions-uk/commit/eeab703558767b25898c3fdafe6754aea0dd507e
