### ISSUE TITLE
AnimeON

### ISSUE THREAD

**Issue by Fqwe1** [CakesTwix/cloudstream-extensions-uk#37]
### Назва сайту

AnimeON

### Посилання на сайт

https://animeon.club/

### Корисна інформація для парсингу

Плеєри ASHDI
https://animeon.club/api/anime *Всі аніме на сайті
https://animeon.club/api/anime/1270 *Інформація про аніме, 1270 - це ID аніме
https://animeon.club/api/anime/similar/1270 *Рекомендації (схожі аніме)
https://animeon.club/search?q=тест *Пошук

### Інша інформація

Є доволі багато студій озвучення

### Який тип медія там є?

- [ ] Фільми
- [ ] Серіали
- [ ] Мультфільми
- [ ] Мультсеріали
- [X] Аніме
- [ ] Дорами
- [ ] 🍓 18+

**Comment by CakesTwix** [comment]
https://github.com/CakesTwix/cloudstream-extensions-uk/commit/eca14921b85c1187805e14c45f9b17f2c925eea3
Додав.
Треба ще переробити логіку обротки плеєрів (проблема у фільмів, тільки одна озвучка)
Ще можна додати рекомендації, якось так
