### ISSUE TITLE
uaserial.club

### ISSUE THREAD

**Issue by pylypenko99** [CakesTwix/cloudstream-extensions-uk#39]
### Назва сайту

uaserial.club

### Посилання на сайт

https://uaserial.club/

### Корисна інформація для парсингу

https://s1.ashdi.vip/video28/serials/gm_mislivecz_na_vogon/01__mislivecz_na_vogon_118249/hls/index.m3u8
blob:https://voidboost.net/2bb8eb25-55b7-4182-8a2f-32cd2ddb6ea2
https://vidsrc.xyz/embed/tv/156688/1/1

### Який тип медія там є?

- [X] Фільми
- [X] Серіали
- [X] Мультфільми
- [X] Мультсеріали
- [X] Аніме
- [X] Дорами
- [ ] 🍓 18+

**Comment by CakesTwix** [comment]
Це не клон сайту https://uaserial.tv/?

**Comment by CakesTwix** [comment]
@pylypenko99, додав https://github.com/CakesTwix/cloudstream-extensions-uk/commit/eef2c62dcc700b4a0d4d58c1f2a28d5c171ca858
