### ISSUE TITLE
Add anitube.in.ua

### ISSUE THREAD

**Issue by NoName3045** [CakesTwix/cloudstream-extensions-uk#4]
Hi, add [anitube.in.ua](https://anitube.in.ua) if possible. Thank you!

**Comment by CakesTwix** [comment]
Я намагався, але там дохуя різних плеєрів, ліниво кожен парсити. Я робив для aniyomi, але застопорився на цих же плеєрах
Наразі хочу просто доповнювати поточні два парсери. Наприклад, нещодавно полагодив парсинг рекомендацій у UAKino

**Comment by CakesTwix** [comment]
Добре, постараюся хоча б ті плеєри, які знаю. Знайшов шматок коду, де зберігаються всі посилання на серії
![image](https://user-images.githubusercontent.com/57946485/219857189-118c147b-4558-4f10-93ce-c10695ba5531.png)

А ще знайшов такий прикол)
![image](https://user-images.githubusercontent.com/57946485/219857195-70236d02-4976-4aac-906d-320f35d76d01.png)

**Comment by CakesTwix** [comment]
In progress
![Screenshot_20230218-153940_CloudStream](https://user-images.githubusercontent.com/57946485/219870420-e6ff7673-2f05-40aa-a184-c33703e36b7d.png)

**Comment by CakesTwix** [comment]
[AnitubeinuaProvider.zip](https://github.com/CakesTwix/cloudstream-extensions-uk/files/10777412/AnitubeinuaProvider.zip)
*rename to *.cs3

Така їбля... Ненавиджу розробників сайту
Поки що пропарсив тільки один плеєр, можеш потикати
