### ISSUE TITLE
Додаткова інформація для uakino.club та uaserials.pro

### ISSUE THREAD

**Issue by eshepelyuk** [CakesTwix/cloudstream-extensions-uk#40]
Чи можна додати до цих двох джерел наступну інформацію, яка доступна на сайтах проте відсутня в CloudStream

* оригінальна назва
* рейтинг imdb

нажаль, не можу додати скріншотів з AndroidTV

**Comment by CakesTwix** [comment]
Привіт. А щось не бачу де англійська назва тайтлів у CS3. Рейтінг вже додав

**Comment by eshepelyuk** [comment]
> Привіт. А щось не бачу де англійська назва тайтлів у CS3. Рейтінг вже додав

ну да її немає, я прошу її додати. десь поруч з українською. на обох сайтах ця назва показується.
