### ISSUE TITLE
UAFLIX

### ISSUE THREAD

**Issue by stanol** [CakesTwix/cloudstream-extensions-uk#43]
### Назва сайту

UAFLIX

### Посилання на сайт

https://uaflix.net/

### Корисна інформація для парсингу

Відеобалансер схожий на ashdi.vip і tortuga.wtf

### Інша інформація

Роблять власний переклад і оперативно додають новинки.

### Який тип медія там є?

- [X] Фільми
- [X] Серіали
- [X] Мультфільми
- [X] Мультсеріали
- [X] Аніме
- [X] Дорами
- [ ] 🍓 18+

**Comment by CakesTwix** [comment]
Нарешті почав робити цей сайт. Майже усе готово
