### ISSUE TITLE
UACHAN

### ISSUE THREAD

**Issue by MrIkso** [CakesTwix/cloudstream-extensions-uk#44]
### Назва сайту

uachan

### Посилання на сайт

https://uachan.com/

### Який тип медія там є?

- [ ] Фільми
- [ ] Серіали
- [ ] Мультфільми
- [ ] Мультсеріали
- [X] Аніме
- [ ] Дорами
- [ ] 🍓 18+

**Comment by CakesTwix** [comment]
Не буду додавати. Причина:
![image](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/57946485/1f0d2b68-df3c-492f-adb2-ecff21eb1ec1)
