### ISSUE TITLE
Субтитри

### ISSUE THREAD

**Issue by ViktorUA78** [CakesTwix/cloudstream-extensions-uk#45]
Чи можна зробити щоб підтягувалися субтитри з джерела?

**Comment by CakesTwix** [comment]
https://github.com/CakesTwix/cloudstream-extensions-uk/commit/240cdd2f6be6b02bab2c9ac7663a911c94e93b55

НАРЕШТІ ДОДАВ, поки що тільки на енеїди для тесту
