### ISSUE TITLE
[Error] AnimeOn

### ISSUE THREAD

**Issue by Fqwe1** [CakesTwix/cloudstream-extensions-uk#46]
**Назва розширення**
AnimeON

**Опис помилки**
При натисканні на будь-яке аніме, виводиться помилка

**Скріншоти**
![Screenshot](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/139431054/5b9e11f7-0124-4ba7-a4fe-f8507be1a5a4)

**Додатковий контекст**
Немає

**Comment by CakesTwix** [comment]
Блііін, забув про це. Завтра буде фікс

**Comment by CakesTwix** [comment]
Fixed.
