### ISSUE TITLE
Багато помилок

### ISSUE THREAD

**Issue by ghost** [CakesTwix/cloudstream-extensions-uk#49]
Тестування в Cloudstream показує юагато помилок:
![Screenshot1](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/139431054/7021a1d3-368f-43d0-aab6-7063df661971)
Можливо краще їх полагодити, дякую за вашу роботу!)

**Comment by CakesTwix** [comment]
Напевно тому що він шукає англійською щось таке,що нема на сайтах

**Comment by Fqwe1** [comment]
> Напевно тому що він шукає англійською щось таке,що нема на сайтах

Я пробував на прикладі Teleportal, знайти шоу "Супермама", то нічого не знаходить

P.s. тест показав що розширення не виводить пошукових результатів

**Comment by CakesTwix** [comment]
Пофіксив. Буду далі дивитися та фіксити, зручна штука
