### ISSUE TITLE
eneyida.tv - відсутність контенту

### ISSUE THREAD

**Issue by dmytrobaiev** [CakesTwix/cloudstream-extensions-uk#51]
Провайдер Eneyida зламався, фільми не відтворюються, бо "Посилань не знайдено", а в серіалах відсутні будь-які серії, і відображається лише "Скоро буде...". Налаштування DNS та Proxy в застосунку не допомогають. Подивися як там з сайтом, а там все працює.

![Screenshot_2024-07-08-11-52-22-288_com lagradost cloudstream3-edit](https://github.com/CakesTwix/cloudstream-extensions-uk/assets/127622853/d221d13f-316e-4605-9835-f75c485b4ffb)

**Comment by CakesTwix** [comment]
eneida.tv fixed
