### ISSUE TITLE
Зміна адреси для uakino.club

### ISSUE THREAD

**Issue by eshepelyuk** [CakesTwix/cloudstream-extensions-uk#53]
### Назва сайту

uakino

### Посилання на сайт

https://uakino.me/

### Корисна інформація для парсингу

Схоже що uakino.club переїхав на нову адресу, чи можна її змінити в додатку чи треба додавати нове джерело ?

### Який тип медія там є?

- [X] Фільми
- [X] Серіали
- [X] Мультфільми
- [X] Мультсеріали
- [ ] Аніме
- [ ] Дорами
- [ ] 🍓 18+

**Comment by CakesTwix** [comment]
У налаштуваннях можна зробити клон сайту з іншим посиланням
Завтра поміняю в коді

**Comment by eshepelyuk** [comment]
> У налаштуваннях можна зробити клон сайту з іншим посиланням
> Завтра поміняю в коді

дякую, пошукаю ще раз в налаштуваннях.

**Comment by eshepelyuk** [comment]
> У налаштуваннях можна зробити клон сайту з іншим посиланням Завтра поміняю в коді

нажаль нічого схожого в налаштуванях не знайшов.

**Comment by CakesTwix** [comment]
Settings -> General > Clone site
Але вже поміняв домен в коді https://github.com/CakesTwix/cloudstream-extensions-uk/commit/3763ae41e0e064dda5789d2db006cf280cf8b149
