### ISSUE TITLE
Не працюють секції в UAkino

### ISSUE THREAD

**Issue by eshepelyuk** [CakesTwix/cloudstream-extensions-uk#54]
**Назва розширення**
UAkino, адреса https://uakino.me

**Опис помилки**
Не працює жодна з секцій, крім фільмів. Не показує кнопку для просмотра. Секція "фільми" працюює в додатку, якщо просто зайти на сайт з планшета - теж все працює.

**Як повторити помилку**

Кроки для відтворення поведінки:
1. Вибрати в програмі uakino
2. Спробувати відкрити будь яку секцію, крім "фільми"

**Додатковий контекст**
Android TV

**Comment by CakesTwix** [comment]
Warning: Undefined array key "HTTP_X_REQUESTED_WITH" in /var/www/www-root/data/www/uakino.me/engine/ajax/playlists.php on line 3
error

Uakino issue, зараз буду дивитися що можна зробити

**Comment by CakesTwix** [comment]
Додав headers.

**Comment by eshepelyuk** [comment]
Дякую, а можна якось зафорсити оновлення плагіну ?
В мене показує що й досі версія 9.

**Comment by eshepelyuk** [comment]
> Додав headers.

дякую все працює
