### ISSUE TITLE
Оновіть README.md

### ISSUE THREAD

**Issue by NoName3045** [CakesTwix/cloudstream-extensions-uk#8]
Оновіть README на це(наведено нижче), мені здається воно більше підходить для цього репозиторію. (Якщо вам не сподобається можете залишити все, як є).

# 🇺🇦 Розширення Cloudstream (Україна)

![GitHub code size](https://img.shields.io/github/languages/code-size/CakesTwix/cloudstream-extensions-uk?style=for-the-badge)
![GitHub Workflow Status](https://img.shields.io/github/actions/workflow/status/CakesTwix/cloudstream-extensions-uk/build.yml?style=for-the-badge)
![Made with Kotlin](https://img.shields.io/badge/Made_with-Kotlin-8051ff?style=for-the-badge&logo=kotlin)

## 📖 Що це таке?
Це спеціальне розширення для перегляду фільмів, серіалів та аніме в якісному українському дубляжу від різних постачальників в стрімінговій програмі [Cloudstream](https://github.com/recloudstream/cloudstream).

## ⚙️ Інсталяція
Скопіюйте посилання нижче і перейдіть в Додаток -> Параметри -> Розширення -> Додати репозиторій
```
https://raw.githubusercontent.com/CakesTwix/cloudstream-extensions-uk/master/repo.json
```

## ✅ Підтримка
Для підтримки пишіть в Telegram [@CakesTwix](https://t.me/CakesTwix) або [@cakestwix_talk](https://t.me/cakestwix_talk)

## 💖 Зробити внесок
Внески завжди вітаються!

## ⭐️ Розробники
- [@CakesTwix](https://www.github.com/CakesTwix)

**Comment by CakesTwix** [comment]
Вауууу, дякую
Зроблю завтра

**Comment by NoName3045** [comment]
Ось [посилання](https://github.com/NoName3045/README-for-cakestwix) на README

**Comment by CakesTwix** [comment]
> Ось [посилання](https://github.com/NoName3045/README-for-cakestwix) на README

Вам потрібно було форкнути мій репозиторій і зробити там зміну і через Pull Request закинути мені

Змінив README, дякую
