### ISSUE TITLE
Adding this to the official repository list

### ISSUE THREAD

**Issue by Blatzar** [CakesTwix/cloudstream-extensions-uk#9]
Great job on the repository!
Do you want this added to the official repository list, to be used on the cloudstream site (https://cloudstream.cf/repos/) and discord?

If you want that, what you want the name to be? "Репозиторій з українським контентом."?

----- Translated:

Чудова робота над pепозиторій! 
Ви хочете, щоб це було додано до офіційного списку репозиторіїв, щоб використовувати на сайті cloudstream (https://cloudstream.cf/repos/) та discord? Якщо ви хочете цього, яким ви хочете, щоб було ім'я? "Репозиторій з українським контентом."?

:people_hugging:

**Comment by CakesTwix** [comment]
I can change it to "Ukrainian providers repository". I made it for myself and my friends, that's why I called it in non-English

**Comment by CakesTwix** [comment]
@Blatzar https://github.com/CakesTwix/cloudstream-extensions-uk/commit/04f489a627d28989c17d2e57379c517f5de8838c

**Comment by Blatzar** [comment]
It'll be fixed 🙏
